// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAc9uWEQygiRLmhpFekD30WX1U2OdkWwNE',
    appId: '1:70243324857:web:78f2f43339c765cddb1c68',
    messagingSenderId: '70243324857',
    projectId: 'chat-app-8ec09',
    authDomain: 'chat-app-8ec09.firebaseapp.com',
    storageBucket: 'chat-app-8ec09.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVUF7-PaahRAO-M_FQnH6Y_ZF3itxf_F8',
    appId: '1:70243324857:android:4e6e1974ceb6acbcdb1c68',
    messagingSenderId: '70243324857',
    projectId: 'chat-app-8ec09',
    storageBucket: 'chat-app-8ec09.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgBiV17YrjbQC0OLEjdjza_cK05ohLHZI',
    appId: '1:70243324857:ios:1e03e416e2563f31db1c68',
    messagingSenderId: '70243324857',
    projectId: 'chat-app-8ec09',
    storageBucket: 'chat-app-8ec09.appspot.com',
    iosBundleId: 'com.example.fristProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgBiV17YrjbQC0OLEjdjza_cK05ohLHZI',
    appId: '1:70243324857:ios:335b7dacf9e04beadb1c68',
    messagingSenderId: '70243324857',
    projectId: 'chat-app-8ec09',
    storageBucket: 'chat-app-8ec09.appspot.com',
    iosBundleId: 'com.example.fristProject.RunnerTests',
  );
}
